/**
 * Executive State CAD — Firestore Seed Script
 * Run: GOOGLE_APPLICATION_CREDENTIALS=<path-to-sa.json> bun run scripts/seed.ts
 */

import { initializeApp, getApps, cert } from 'firebase-admin/app'
import { getFirestore, WriteBatch } from 'firebase-admin/firestore'

// ─── Firebase Init ────────────────────────────────────────────────────────────

const credPath = process.env.GOOGLE_APPLICATION_CREDENTIALS
if (!credPath) {
  console.error('ERROR: GOOGLE_APPLICATION_CREDENTIALS env var is not set.')
  process.exit(1)
}

if (!getApps().length) {
  initializeApp({ credential: cert(credPath) })
}

const db = getFirestore()

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Flush a batch and start a new one, logging progress */
async function flushBatch(batch: WriteBatch, label: string): Promise<WriteBatch> {
  await batch.commit()
  console.log(`  ✓ flushed batch: ${label}`)
  return db.batch()
}

/** Split an array into chunks of at most `size` */
function chunks<T>(arr: T[], size: number): T[][] {
  const result: T[][] = []
  for (let i = 0; i < arr.length; i += size) result.push(arr.slice(i, i + size))
  return result
}

// ─── 1. system_config/settings ───────────────────────────────────────────────

async function seedSystemConfig() {
  console.log('\n[1/3] Seeding system_config/settings …')
  const ref = db.collection('system_config').doc('settings')
  await ref.set(
    {
      guildId: '1395547996749299885',
      cadName: 'Executive State CAD',
      departments: ['LSPD', 'SAST', 'SAFD', 'SAMS', 'DISPATCH'],
      panicAlertWebhook: '',
      callWebhook: '',
      maintenanceMode: false,
      updatedAt: Date.now(),
    },
    { merge: true }
  )
  console.log('  ✓ system_config/settings written')
}

// ─── 2. ten_codes ─────────────────────────────────────────────────────────────

interface TenCode {
  code: string
  label: string
  description: string
  type: 'ten_code' | 'signal'
  category: 'status' | 'dispatch' | 'emergency' | 'admin' | 'transport'
  priority: boolean
  applicableDepts: string[]
}

const TEN_CODES: TenCode[] = [
  // ── Status codes ──
  {
    code: '10-6',
    label: 'Busy',
    description: 'Unit is busy, stand by.',
    type: 'ten_code',
    category: 'status',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-7',
    label: 'Out of Service',
    description: 'Unit is out of service / off duty.',
    type: 'ten_code',
    category: 'status',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-8',
    label: 'In Service',
    description: 'Unit is in service and available.',
    type: 'ten_code',
    category: 'status',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-10',
    label: 'Off Duty',
    description: 'Unit is off duty.',
    type: 'ten_code',
    category: 'status',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-23',
    label: 'Arrived on Scene',
    description: 'Unit has arrived at the scene.',
    type: 'ten_code',
    category: 'status',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-42',
    label: 'End of Tour / Shift',
    description: 'Officer ending their tour of duty.',
    type: 'ten_code',
    category: 'status',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-97',
    label: 'Arrived at Scene',
    description: 'Unit has arrived and is on scene.',
    type: 'ten_code',
    category: 'status',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-98',
    label: 'Assignment Complete',
    description: 'Assignment / call is complete.',
    type: 'ten_code',
    category: 'status',
    priority: false,
    applicableDepts: [],
  },
  // ── Dispatch codes ──
  {
    code: '10-4',
    label: 'Acknowledged / Copy',
    description: 'Message received and understood.',
    type: 'ten_code',
    category: 'dispatch',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-9',
    label: 'Repeat',
    description: 'Please repeat your last transmission.',
    type: 'ten_code',
    category: 'dispatch',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-11',
    label: 'Identify Frequency',
    description: 'Identify the frequency / animal at large.',
    type: 'ten_code',
    category: 'dispatch',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-15',
    label: 'Suspect in Custody',
    description: 'Suspect or prisoner in custody.',
    type: 'ten_code',
    category: 'dispatch',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-20',
    label: 'Location',
    description: 'What is your location? / My location is …',
    type: 'ten_code',
    category: 'dispatch',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-21',
    label: 'Call by Telephone',
    description: 'Call this station/unit by telephone.',
    type: 'ten_code',
    category: 'dispatch',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-25',
    label: 'Report to Scene',
    description: 'Report to or meet at the scene.',
    type: 'ten_code',
    category: 'dispatch',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-32',
    label: 'Man with Gun',
    description: 'Subject with a firearm reported.',
    type: 'ten_code',
    category: 'dispatch',
    priority: true,
    applicableDepts: ['LSPD', 'SAST'],
  },
  {
    code: '10-35',
    label: 'Major Crime Alert',
    description: 'Major crime alert in progress.',
    type: 'ten_code',
    category: 'dispatch',
    priority: true,
    applicableDepts: [],
  },
  {
    code: '10-36',
    label: 'Correct Time',
    description: 'What is the correct time?',
    type: 'ten_code',
    category: 'admin',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-37',
    label: 'Investigate Suspicious Vehicle',
    description: 'Investigate a suspicious vehicle.',
    type: 'ten_code',
    category: 'dispatch',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-38',
    label: 'Traffic Stop',
    description: 'Unit conducting a traffic stop.',
    type: 'ten_code',
    category: 'dispatch',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-39',
    label: 'Urgent — Use Lights and Siren',
    description: 'Respond code 3 — lights and siren.',
    type: 'ten_code',
    category: 'dispatch',
    priority: true,
    applicableDepts: [],
  },
  {
    code: '10-51',
    label: 'Wrecker Requested',
    description: 'Request a tow truck / wrecker.',
    type: 'ten_code',
    category: 'transport',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-52',
    label: 'Ambulance Requested',
    description: 'Request an ambulance at the scene.',
    type: 'ten_code',
    category: 'dispatch',
    priority: true,
    applicableDepts: ['LSPD', 'SAST', 'SAMS'],
  },
  {
    code: '10-55',
    label: 'Intoxicated Driver',
    description: 'Intoxicated driver reported or stopped.',
    type: 'ten_code',
    category: 'dispatch',
    priority: false,
    applicableDepts: ['LSPD', 'SAST'],
  },
  {
    code: '10-57',
    label: 'Hit and Run',
    description: 'Hit and run collision.',
    type: 'ten_code',
    category: 'dispatch',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-71',
    label: 'Shooting',
    description: 'Shooting in progress or reported.',
    type: 'ten_code',
    category: 'dispatch',
    priority: true,
    applicableDepts: [],
  },
  {
    code: '10-80',
    label: 'Vehicle Pursuit',
    description: 'Vehicle pursuit in progress.',
    type: 'ten_code',
    category: 'dispatch',
    priority: true,
    applicableDepts: [],
  },
  {
    code: '10-87',
    label: 'Meet at Location',
    description: 'Meet at specified location.',
    type: 'ten_code',
    category: 'dispatch',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-99',
    label: 'Officer in Distress / Panic',
    description: 'Officer needs immediate assistance — all units respond.',
    type: 'ten_code',
    category: 'emergency',
    priority: true,
    applicableDepts: [],
  },
  // ── Additional admin / misc ──
  {
    code: '10-1',
    label: 'Poor Reception',
    description: 'Cannot copy — poor radio reception.',
    type: 'ten_code',
    category: 'admin',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-2',
    label: 'Good Reception',
    description: 'Radio reception is clear.',
    type: 'ten_code',
    category: 'admin',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-3',
    label: 'Stop Transmitting',
    description: 'Stop transmitting — clear the channel.',
    type: 'ten_code',
    category: 'admin',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-13',
    label: 'Weather / Road Conditions',
    description: 'Report weather and road conditions.',
    type: 'ten_code',
    category: 'admin',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-14',
    label: 'Convoy Escort',
    description: 'Providing convoy or prisoner escort.',
    type: 'ten_code',
    category: 'transport',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-16',
    label: 'Domestic Disturbance',
    description: 'Domestic disturbance call.',
    type: 'ten_code',
    category: 'dispatch',
    priority: false,
    applicableDepts: ['LSPD', 'SAST'],
  },
  {
    code: '10-17',
    label: 'Meet Complainant',
    description: 'Meet the complainant.',
    type: 'ten_code',
    category: 'dispatch',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-19',
    label: 'Return to Station',
    description: 'Return to your station.',
    type: 'ten_code',
    category: 'admin',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-26',
    label: 'Detaining Suspect',
    description: 'Detaining a suspect — stand by.',
    type: 'ten_code',
    category: 'dispatch',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-27',
    label: 'License Check',
    description: "Run a driver's license check.",
    type: 'ten_code',
    category: 'dispatch',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-28',
    label: 'Vehicle Registration Check',
    description: 'Run a vehicle registration check.',
    type: 'ten_code',
    category: 'dispatch',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-29',
    label: 'Warrants Check',
    description: 'Check subject for outstanding warrants.',
    type: 'ten_code',
    category: 'dispatch',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-30',
    label: 'Does Not Conform to Rules',
    description: 'Subject does not conform to regulations.',
    type: 'ten_code',
    category: 'admin',
    priority: false,
    applicableDepts: [],
  },
  {
    code: '10-31',
    label: 'Crime in Progress',
    description: 'Crime in progress at this location.',
    type: 'ten_code',
    category: 'dispatch',
    priority: true,
    applicableDepts: [],
  },
  {
    code: '10-33',
    label: 'Emergency — All Units Stand By',
    description: 'Emergency — all units clear the channel.',
    type: 'ten_code',
    category: 'emergency',
    priority: true,
    applicableDepts: [],
  },
  {
    code: '10-34',
    label: 'Riot',
    description: 'Riot in progress.',
    type: 'ten_code',
    category: 'emergency',
    priority: true,
    applicableDepts: [],
  },
  // ── Signal ──
  {
    code: 'Signal 100',
    label: 'All Units Alert',
    description: 'All units — major incident, all available units respond immediately.',
    type: 'signal',
    category: 'emergency',
    priority: true,
    applicableDepts: [],
  },
]

async function seedTenCodes() {
  console.log(`\n[2/3] Seeding ten_codes (${TEN_CODES.length} documents) …`)
  const col = db.collection('ten_codes')
  for (const group of chunks(TEN_CODES, 490)) {
    let batch = db.batch()
    let count = 0
    for (const entry of group) {
      const docId = entry.code.replace(/[\s/]/g, '_')
      batch.set(col.doc(docId), entry, { merge: true })
      count++
    }
    await flushBatch(batch, `${count} ten_codes`)
  }
  console.log(`  ✓ ${TEN_CODES.length} ten_codes seeded`)
}

// ─── 3. penal_codes ───────────────────────────────────────────────────────────

interface PenalCode {
  code: string
  title: string
  description: string
  category: string
  severity: 'infraction' | 'misdemeanor' | 'felony' | 'capital'
  type: 'arrest' | 'citation' | 'both'
  fine: number | null
  jailTime: string | null
  licensePoints: number | null
  licenseAction: 'none' | 'suspend' | 'revoke'
  searchable: boolean
  createdAt: number
}

const NOW = Date.now()

const PENAL_CODES: PenalCode[] = [
  // ── crimes_against_persons ──
  {
    code: '187 PC',
    title: 'Murder',
    description: 'The unlawful killing of a human being with malice aforethought.',
    category: 'crimes_against_persons',
    severity: 'capital',
    type: 'arrest',
    fine: null,
    jailTime: 'Life / 25 years to life',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '664/187 PC',
    title: 'Attempted Murder',
    description: 'Attempting to kill a human being with intent.',
    category: 'crimes_against_persons',
    severity: 'felony',
    type: 'arrest',
    fine: null,
    jailTime: '15–30 years',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '245 PC',
    title: 'Assault with a Deadly Weapon',
    description: 'Assault upon a person with a deadly weapon or by means of force likely to produce great bodily injury.',
    category: 'crimes_against_persons',
    severity: 'felony',
    type: 'arrest',
    fine: 10000,
    jailTime: '2–8 years',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '240 PC',
    title: 'Assault',
    description: 'An unlawful attempt, coupled with present ability, to commit a violent injury on the person of another.',
    category: 'crimes_against_persons',
    severity: 'misdemeanor',
    type: 'arrest',
    fine: 2000,
    jailTime: '6 months',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '242 PC',
    title: 'Battery',
    description: 'Willful and unlawful use of force or violence upon the person of another.',
    category: 'crimes_against_persons',
    severity: 'misdemeanor',
    type: 'arrest',
    fine: 2000,
    jailTime: '6 months',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '207 PC',
    title: 'Kidnapping',
    description: 'Forcibly, or by any other means of instilling fear, stealing or taking away a person.',
    category: 'crimes_against_persons',
    severity: 'felony',
    type: 'arrest',
    fine: null,
    jailTime: '3–8 years',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '261 PC',
    title: 'Rape',
    description: 'Non-consensual sexual intercourse accomplished by means of force, violence, or threat.',
    category: 'crimes_against_persons',
    severity: 'felony',
    type: 'arrest',
    fine: null,
    jailTime: '3–8 years',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '211 PC',
    title: 'Robbery',
    description: 'Felonious taking of personal property in the possession of another, from their person or immediate presence, by means of force or fear.',
    category: 'crimes_against_persons',
    severity: 'felony',
    type: 'arrest',
    fine: null,
    jailTime: '2–5 years',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '215 PC',
    title: 'Carjacking',
    description: 'Taking of a motor vehicle from the person or immediate presence of another against their will by force or fear.',
    category: 'crimes_against_persons',
    severity: 'felony',
    type: 'arrest',
    fine: null,
    jailTime: '3–9 years',
    licensePoints: null,
    licenseAction: 'revoke',
    searchable: true,
    createdAt: NOW,
  },
  // ── crimes_against_property ──
  {
    code: '459 PC',
    title: 'Burglary',
    description: 'Entering a structure with intent to commit theft or any felony therein.',
    category: 'crimes_against_property',
    severity: 'felony',
    type: 'arrest',
    fine: 10000,
    jailTime: '2–6 years',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '487 PC',
    title: 'Grand Theft',
    description: 'Theft of property or money valued over $950, or theft of a vehicle or firearm.',
    category: 'crimes_against_property',
    severity: 'felony',
    type: 'arrest',
    fine: 5000,
    jailTime: '16 months – 3 years',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '484 PC',
    title: 'Petty Theft',
    description: 'Theft of property valued at $950 or less.',
    category: 'crimes_against_property',
    severity: 'misdemeanor',
    type: 'both',
    fine: 1000,
    jailTime: '6 months',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '594 PC',
    title: 'Vandalism',
    description: 'Defacing, damaging, or destroying real or personal property not one\'s own.',
    category: 'crimes_against_property',
    severity: 'misdemeanor',
    type: 'both',
    fine: 1500,
    jailTime: '1 year',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '602 PC',
    title: 'Trespassing',
    description: 'Entering or remaining on private property without permission.',
    category: 'crimes_against_property',
    severity: 'misdemeanor',
    type: 'both',
    fine: 500,
    jailTime: '6 months',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '503 PC',
    title: 'Embezzlement',
    description: 'Fraudulent appropriation of property by a person to whom it has been entrusted.',
    category: 'crimes_against_property',
    severity: 'felony',
    type: 'arrest',
    fine: 10000,
    jailTime: '16 months – 3 years',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  // ── drug_offenses ──
  {
    code: '11350 HS',
    title: 'Possession of Narcotics',
    description: 'Possession of a controlled substance without a valid prescription.',
    category: 'drug_offenses',
    severity: 'misdemeanor',
    type: 'arrest',
    fine: 1000,
    jailTime: '1 year',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '11351 HS',
    title: 'Possession of Narcotics for Sale',
    description: 'Possession of a controlled substance with intent to sell.',
    category: 'drug_offenses',
    severity: 'felony',
    type: 'arrest',
    fine: 20000,
    jailTime: '2–4 years',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '11352 HS',
    title: 'Transportation of Narcotics',
    description: 'Transporting, importing, selling, or distributing a controlled substance.',
    category: 'drug_offenses',
    severity: 'felony',
    type: 'arrest',
    fine: 20000,
    jailTime: '3–9 years',
    licensePoints: null,
    licenseAction: 'revoke',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '11357 HS',
    title: 'Possession of Marijuana',
    description: 'Possession of marijuana in excess of the legal limit.',
    category: 'drug_offenses',
    severity: 'infraction',
    type: 'citation',
    fine: 250,
    jailTime: null,
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '11359 HS',
    title: 'Possession of Marijuana for Sale',
    description: 'Possession of marijuana with intent to sell or distribute.',
    category: 'drug_offenses',
    severity: 'misdemeanor',
    type: 'arrest',
    fine: 5000,
    jailTime: '6 months',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  // ── traffic_violations ──
  {
    code: '22350 VC',
    title: 'Unsafe Speed',
    description: 'Driving at a speed that is not reasonable or prudent given weather, visibility, and traffic conditions.',
    category: 'traffic_violations',
    severity: 'infraction',
    type: 'citation',
    fine: 500,
    jailTime: null,
    licensePoints: 1,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '22349 VC',
    title: 'Speeding — Over 100 mph',
    description: 'Operating a vehicle in excess of 100 mph on a highway.',
    category: 'traffic_violations',
    severity: 'misdemeanor',
    type: 'both',
    fine: 1000,
    jailTime: '30 days',
    licensePoints: 2,
    licenseAction: 'suspend',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '21651 VC',
    title: 'Wrong Side of Road',
    description: 'Driving on the wrong side of a divided road.',
    category: 'traffic_violations',
    severity: 'misdemeanor',
    type: 'citation',
    fine: 750,
    jailTime: null,
    licensePoints: 1,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '23152 VC',
    title: 'Driving Under the Influence (DUI)',
    description: 'Operating a vehicle while impaired by alcohol or drugs.',
    category: 'traffic_violations',
    severity: 'misdemeanor',
    type: 'arrest',
    fine: 2000,
    jailTime: '6 months – 1 year',
    licensePoints: 2,
    licenseAction: 'suspend',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '23103 VC',
    title: 'Reckless Driving',
    description: 'Operating a vehicle in willful or wanton disregard for the safety of persons or property.',
    category: 'traffic_violations',
    severity: 'misdemeanor',
    type: 'arrest',
    fine: 1000,
    jailTime: '5–90 days',
    licensePoints: 2,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '20001 VC',
    title: 'Hit and Run — Felony',
    description: 'Leaving the scene of an accident involving injury or death.',
    category: 'traffic_violations',
    severity: 'felony',
    type: 'arrest',
    fine: 10000,
    jailTime: '2–4 years',
    licensePoints: 2,
    licenseAction: 'revoke',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '20002 VC',
    title: 'Hit and Run — Misdemeanor',
    description: 'Leaving the scene of an accident involving only property damage.',
    category: 'traffic_violations',
    severity: 'misdemeanor',
    type: 'arrest',
    fine: 1500,
    jailTime: '6 months',
    licensePoints: 2,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '14601 VC',
    title: 'Driving on Suspended License',
    description: 'Operating a vehicle with a suspended or revoked driver\'s license.',
    category: 'traffic_violations',
    severity: 'misdemeanor',
    type: 'arrest',
    fine: 1500,
    jailTime: '10 days – 6 months',
    licensePoints: 2,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '4000 VC',
    title: 'No Vehicle Registration',
    description: 'Operating a vehicle without valid registration.',
    category: 'traffic_violations',
    severity: 'infraction',
    type: 'citation',
    fine: 200,
    jailTime: null,
    licensePoints: 0,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '16028 VC',
    title: 'No Proof of Insurance',
    description: 'Failure to provide evidence of financial responsibility (insurance).',
    category: 'traffic_violations',
    severity: 'infraction',
    type: 'citation',
    fine: 500,
    jailTime: null,
    licensePoints: 0,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '5200 VC',
    title: 'No Front License Plate',
    description: 'Operating a vehicle without a required front license plate.',
    category: 'traffic_violations',
    severity: 'infraction',
    type: 'citation',
    fine: 200,
    jailTime: null,
    licensePoints: 0,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '21453 VC',
    title: 'Failure to Stop at Red Light',
    description: 'Failing to obey a traffic signal showing a steady red light.',
    category: 'traffic_violations',
    severity: 'infraction',
    type: 'citation',
    fine: 400,
    jailTime: null,
    licensePoints: 1,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '22450 VC',
    title: 'Failure to Stop at Stop Sign',
    description: 'Failure to come to a complete stop at a stop sign.',
    category: 'traffic_violations',
    severity: 'infraction',
    type: 'citation',
    fine: 250,
    jailTime: null,
    licensePoints: 1,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  // ── weapons_offenses ──
  {
    code: '25400 PC',
    title: 'Carrying a Concealed Firearm',
    description: 'Carrying a concealed firearm on one\'s person or in a vehicle without authorization.',
    category: 'weapons_offenses',
    severity: 'felony',
    type: 'arrest',
    fine: 10000,
    jailTime: '16 months – 3 years',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '25850 PC',
    title: 'Carrying a Loaded Firearm in Public',
    description: 'Carrying a loaded firearm in a public place or on a public street.',
    category: 'weapons_offenses',
    severity: 'misdemeanor',
    type: 'arrest',
    fine: 5000,
    jailTime: '1 year',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '12022 PC',
    title: 'Armed in Commission of a Crime',
    description: 'Being armed with a firearm during the commission of a felony.',
    category: 'weapons_offenses',
    severity: 'felony',
    type: 'arrest',
    fine: null,
    jailTime: '1–5 years (consecutive)',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '246 PC',
    title: 'Shooting at an Occupied Vehicle',
    description: 'Discharging a firearm at an occupied motor vehicle or aircraft.',
    category: 'weapons_offenses',
    severity: 'felony',
    type: 'arrest',
    fine: null,
    jailTime: '3–7 years',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '417 PC',
    title: 'Brandishing a Weapon',
    description: 'Drawing or exhibiting a deadly weapon in a rude, angry, or threatening manner.',
    category: 'weapons_offenses',
    severity: 'misdemeanor',
    type: 'arrest',
    fine: 1000,
    jailTime: '30 days – 6 months',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '26100 PC',
    title: 'Discharge of Firearm from Motor Vehicle',
    description: 'Discharging a firearm from a motor vehicle.',
    category: 'weapons_offenses',
    severity: 'felony',
    type: 'arrest',
    fine: null,
    jailTime: '3–7 years',
    licensePoints: null,
    licenseAction: 'revoke',
    searchable: true,
    createdAt: NOW,
  },
  // ── public_order ──
  {
    code: '148 PC',
    title: 'Obstruction / Resisting Arrest',
    description: 'Willfully resisting, delaying, or obstructing any peace officer in the discharge of their duties.',
    category: 'public_order',
    severity: 'misdemeanor',
    type: 'arrest',
    fine: 1000,
    jailTime: '1 year',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '647 PC',
    title: 'Disorderly Conduct',
    description: 'Engaging in conduct that disturbs the public peace, including solicitation, loitering, or public intoxication.',
    category: 'public_order',
    severity: 'misdemeanor',
    type: 'both',
    fine: 500,
    jailTime: '6 months',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '409 PC',
    title: 'Failure to Disperse',
    description: 'Remaining present at a riot or unlawful assembly after a lawful order to disperse.',
    category: 'public_order',
    severity: 'misdemeanor',
    type: 'arrest',
    fine: 500,
    jailTime: '6 months',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '415 PC',
    title: 'Disturbing the Peace',
    description: 'Unlawfully fighting, making loud and unreasonable noise, or using offensive words in a public place.',
    category: 'public_order',
    severity: 'misdemeanor',
    type: 'both',
    fine: 400,
    jailTime: '90 days',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '370 PC',
    title: 'Public Nuisance',
    description: 'Creating a condition or engaging in an act that is injurious to the public health or safety.',
    category: 'public_order',
    severity: 'misdemeanor',
    type: 'citation',
    fine: 500,
    jailTime: null,
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '403 PC',
    title: 'Disruption of Public Meeting',
    description: 'Willfully disturbing or breaking up any lawful meeting or assembly.',
    category: 'public_order',
    severity: 'misdemeanor',
    type: 'both',
    fine: 500,
    jailTime: '6 months',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  // ── government_offenses ──
  {
    code: '69 PC',
    title: 'Obstruct / Resist Executive Officer',
    description: 'Attempting by threats or violence to deter or prevent an executive officer from performing any duty.',
    category: 'government_offenses',
    severity: 'felony',
    type: 'arrest',
    fine: 10000,
    jailTime: '16 months – 3 years',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '67 PC',
    title: 'Bribery of a Public Official',
    description: 'Giving or offering a bribe to an executive officer with corrupt intent.',
    category: 'government_offenses',
    severity: 'felony',
    type: 'arrest',
    fine: 10000,
    jailTime: '2–4 years',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '182 PC',
    title: 'Conspiracy',
    description: 'Agreeing with one or more persons to commit a crime and taking an overt act toward that crime.',
    category: 'government_offenses',
    severity: 'felony',
    type: 'arrest',
    fine: 10000,
    jailTime: 'Varies by underlying offense',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '4532 PC',
    title: 'Escape from Custody',
    description: 'Escaping from lawful custody, including prison, jail, or during transport.',
    category: 'government_offenses',
    severity: 'felony',
    type: 'arrest',
    fine: null,
    jailTime: '16 months – 4 years (consecutive)',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '32 PC',
    title: 'Accessory After the Fact',
    description: 'Knowingly harboring, concealing, or aiding a principal felon after the crime.',
    category: 'government_offenses',
    severity: 'felony',
    type: 'arrest',
    fine: 5000,
    jailTime: '16 months – 3 years',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '31 PC',
    title: 'Aiding and Abetting',
    description: 'Assisting, facilitating, or encouraging another person to commit a crime.',
    category: 'government_offenses',
    severity: 'felony',
    type: 'arrest',
    fine: null,
    jailTime: 'Same as principal offense',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '136.1 PC',
    title: 'Witness Intimidation',
    description: 'Knowingly and maliciously preventing or dissuading a witness from testifying.',
    category: 'government_offenses',
    severity: 'felony',
    type: 'arrest',
    fine: 10000,
    jailTime: '2–4 years',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  // ── financial_crimes ──
  {
    code: '470 PC',
    title: 'Forgery',
    description: 'Falsely making, altering, or forging any written document with intent to defraud.',
    category: 'financial_crimes',
    severity: 'felony',
    type: 'arrest',
    fine: 10000,
    jailTime: '16 months – 3 years',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '532 PC',
    title: 'Fraud',
    description: 'Obtaining money, property, or services through deception, misrepresentation, or false pretenses.',
    category: 'financial_crimes',
    severity: 'felony',
    type: 'arrest',
    fine: 10000,
    jailTime: '16 months – 3 years',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '518 PC',
    title: 'Extortion',
    description: 'Obtaining property from another, with their consent, induced by wrongful use of force or fear.',
    category: 'financial_crimes',
    severity: 'felony',
    type: 'arrest',
    fine: 10000,
    jailTime: '2–4 years',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '496 PC',
    title: 'Receiving Stolen Property',
    description: 'Buying or receiving any property that has been stolen or obtained through extortion.',
    category: 'financial_crimes',
    severity: 'felony',
    type: 'arrest',
    fine: 5000,
    jailTime: '16 months – 3 years',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '550 VC',
    title: 'Insurance Fraud',
    description: 'Knowingly making false or fraudulent claims to an insurance company.',
    category: 'financial_crimes',
    severity: 'felony',
    type: 'arrest',
    fine: 150000,
    jailTime: '2–5 years',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
  {
    code: '186.10 PC',
    title: 'Money Laundering',
    description: 'Conducting a financial transaction to promote criminal activity or conceal the source of criminal proceeds.',
    category: 'financial_crimes',
    severity: 'felony',
    type: 'arrest',
    fine: 250000,
    jailTime: '2–4 years',
    licensePoints: null,
    licenseAction: 'none',
    searchable: true,
    createdAt: NOW,
  },
]

async function seedPenalCodes() {
  console.log(`\n[3/3] Seeding penal_codes (${PENAL_CODES.length} documents) …`)
  const col = db.collection('penal_codes')
  for (const group of chunks(PENAL_CODES, 490)) {
    let batch = db.batch()
    let count = 0
    for (const entry of group) {
      const docId = entry.code.replace(/[\s/]/g, '_')
      batch.set(col.doc(docId), entry, { merge: true })
      count++
    }
    await flushBatch(batch, `${count} penal_codes`)
  }
  console.log(`  ✓ ${PENAL_CODES.length} penal_codes seeded`)
}

// ─── Main ────────────────────────────────────────────────────────────────────

async function main() {
  console.log('╔══════════════════════════════════════════╗')
  console.log('║  Executive State CAD — Firestore Seeder  ║')
  console.log('╚══════════════════════════════════════════╝')
  const start = Date.now()

  await seedSystemConfig()
  await seedTenCodes()
  await seedPenalCodes()

  const elapsed = ((Date.now() - start) / 1000).toFixed(2)
  console.log(`\n✅ Seed complete in ${elapsed}s`)
  console.log(`   system_config: 1 doc`)
  console.log(`   ten_codes:     ${TEN_CODES.length} docs`)
  console.log(`   penal_codes:   ${PENAL_CODES.length} docs`)
  process.exit(0)
}

main().catch((err) => {
  console.error('Seed failed:', err)
  process.exit(1)
})
